before:
  hooks:
    - go mod download
    - ./tools/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - completions/*
nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    description: TODO
    maintainer: Johan Lindell <johan@lindell.me>
    license: Apache-2.0
    contents:
      - src: ./completions/go-cli-template.bash
        dst: /etc/bash_completion.d/go-cli-template
      - src: ./completions/go-cli-template.fish
        dst: /usr/share/fish/completions/go-cli-template.fish
      - src: ./completions/go-cli-template.zsh
        dst: /usr/local/share/zsh/site-functions/_go-cli-template
    formats:
    - deb
    - rpm
    recommends:
    - git
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: go-cli-template
    repository:
      owner: lindell
      name: homebrew-go-cli-template # TODO: Create this repo
    goarm: 6
    commit_author:
      name: Johan Lindell
      email: johan@lindell.me
    description: TODO
    homepage: https://github.com/lindell/go-cli-template
    license: "Apache-2.0"
    folder: Formula
    install: |-
      bin.install "go-cli-template"
      bash_completion.install "completions/go-cli-template.bash" => "go-cli-template"
      zsh_completion.install "completions/go-cli-template.zsh" => "_go-cli-template"
      fish_completion.install "completions/go-cli-template.fish"
    test: |
      system "#{bin}/go-cli-template", "version"
